<div class="loadingio-spinner-bars-8bvmy8hg10b">
  <div class="ldio-qcdk0bgs82l">
    <div />
    <div />
    <div />
    <div />
  </div>
</div>

<style>
  @keyframes ldio-qcdk0bgs82l {
    0% {
      opacity: 1;
    }
    50% {
      opacity: 0.5;
    }
    100% {
      opacity: 1;
    }
  }
  .ldio-qcdk0bgs82l div {
    position: absolute;
    width: 8px;
    height: 40px;
    top: 30px;
    animation: ldio-qcdk0bgs82l 1s cubic-bezier(0.5, 0, 0.5, 1) infinite;
  }
  .ldio-qcdk0bgs82l div:nth-child(1) {
    transform: translate(16px, 0);
    background: #e15b64;
    animation-delay: -0.6s;
  }
  .ldio-qcdk0bgs82l div:nth-child(2) {
    transform: translate(36px, 0);
    background: #f47e60;
    animation-delay: -0.4s;
  }
  .ldio-qcdk0bgs82l div:nth-child(3) {
    transform: translate(56px, 0);
    background: #f8b26a;
    animation-delay: -0.2s;
  }
  .ldio-qcdk0bgs82l div:nth-child(4) {
    transform: translate(76px, 0);
    background: #abbd81;
    animation-delay: -1s;
  }
  .loadingio-spinner-bars-8bvmy8hg10b {
    width: 90px;
    height: 90px;
    display: inline-block;
    overflow: hidden;
    background: none;
  }
  .ldio-qcdk0bgs82l {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(0.9);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-qcdk0bgs82l div {
    box-sizing: content-box;
  }
  /* generated by https://loading.io/ */
</style>
